const columns = ["inbox", "contacts", "ready", "waiting", "archive"];
const t = key => window.signalboardI18n?.t?.(key) || key;
const columnName = id => t(id);
const starterJobs = [
  { id: 1, company: "Fjord & Co.", role: "Head of Growth", status: "inbox", priority: "high", note: "Neue Wachstumsrolle – wahrscheinlich hoher Zeitdruck.", contacts: [{ name: "Mara Klein", title: "Founder & CEO" }, { name: "Jonas Weber", title: "COO" }] },
  { id: 2, company: "Noveo", role: "Product Marketing Manager", status: "inbox", priority: "medium", note: "B2B SaaS; guter Fit für einen schnellen Go-to-Market-Start.", contacts: [{ name: "Alina Roth", title: "VP Marketing" }] },
  { id: 3, company: "Kite Mobility", role: "Operations Lead", status: "qualified", priority: "high", note: "Skalierung im DACH-Markt. Interim-Setup anbieten.", contacts: [{ name: "Felix Brandt", title: "Co-Founder" }, { name: "Lea Scholz", title: "Head of Operations" }] },
  { id: 4, company: "morrow studio", role: "Senior Project Manager", status: "contacts", priority: "medium", note: "Passende Rolle; Entscheider auswählen und Nachricht schärfen.", contacts: [{ name: "Nina Berg", title: "Managing Director" }, { name: "David Hahn", title: "Creative Director" }] },
  { id: 5, company: "Vela", role: "Growth Strategist", status: "ready", priority: "high", note: "Kontakt und Text sind vorbereitet.", selectedContact: "Sophie Lange", contacts: [{ name: "Sophie Lange", title: "Chief Commercial Officer" }] },
  { id: 6, company: "Lumen AI", role: "Partnerships Manager", status: "waiting", priority: "medium", note: "Anfrage verschickt · Follow-up in 5 Tagen.", selectedContact: "Tobias Kern", contacts: [{ name: "Tobias Kern", title: "Founder" }] }
];
let jobs = JSON.parse(localStorage.getItem("signalboard-jobs") || "null") || starterJobs;
const testCompanies = new Set(["Fjord & Co.", "Noveo", "Kite Mobility", "morrow studio", "Vela", "Lumen AI"]);
jobs = jobs.filter(job => !testCompanies.has(job.company));
jobs.forEach(job => { if (job.status === "qualified") job.status = "contacts"; });
let savedSearches = JSON.parse(localStorage.getItem("signalboard-searches") || "null") || [
  { id: 1, title: "Product Marketing", location: "Berlin · Remote", keywords: "B2B SaaS", active: true },
  { id: 2, title: "Operations & Growth", location: "DACH", keywords: "Scale-up", active: true },
  { id: 3, title: "Projektmanagement", location: "Berlin", keywords: "Agentur, Digital", active: false }
];
let ignoredJobs = JSON.parse(localStorage.getItem("signalboard-ignored-jobs") || "[]");
let filter = "all", query = "", draggingId = null, editingSearchId = null, editingJobId = null, returnToContacts = false, manualContactTarget = null, pendingDiscoveryCount = 0;
const board = document.querySelector("#board"), template = document.querySelector("#cardTemplate"), detailDialog = document.querySelector("#detailDialog");
function save(){ localStorage.setItem("signalboard-jobs", JSON.stringify(jobs)); localStorage.setItem("signalboard-searches", JSON.stringify(savedSearches)); localStorage.setItem("signalboard-ignored-jobs",JSON.stringify(ignoredJobs)); window.signalboardAuth?.saveState({jobs, searches:savedSearches,ignoredJobs}); }
function updateSearchButton(){const button=document.querySelector("#searchNow");if(button&&!button.disabled)button.textContent=pendingDiscoveryCount?`◌ Jetzt suchen · ${pendingDiscoveryCount} neu`:"◌ Jetzt suchen";}
function cleanUrl(value=""){try{const url=new URL(value);[...url.searchParams.keys()].filter(key=>/^utm_|^trk$|^ref$/i.test(key)).forEach(key=>url.searchParams.delete(key));url.hash="";return url.toString().replace(/\/$/,"")}catch{return String(value).trim().toLowerCase();}}
function jobKey(job){return cleanUrl(job.url||job.jobLink||"")||`${String(job.company||"").toLowerCase()}|${String(job.title||job.role||"").toLowerCase()}|${String(job.location||"").toLowerCase()}`}
function isKnownJob(job){const key=jobKey(job);return jobs.some(item=>jobKey(item)===key)||ignoredJobs.some(item=>item.key===key)}
function ignoreJob(job){const key=jobKey(job);if(!ignoredJobs.some(item=>item.key===key))ignoredJobs.unshift({key,url:cleanUrl(job.url||job.jobLink||""),company:job.company||"",role:job.title||job.role||"",ignoredAt:new Date().toISOString()});save()}
save();
function initials(name){ return (name || "SB").split(" ").map(x=>x[0]).join("").slice(0,2); }
function nextLabel(status){ return ({ inbox:t("qualify"), qualified:t("findContacts"), contacts:t("chooseContact"), ready:t("send"), waiting:t("followUp") })[status]; }
const WAITING_MS=7*24*60*60*1000;
function setStatus(job,status){ job.status=status; if(status==="waiting") job.waitingSince=new Date().toISOString(); }
function waitInfo(job){ const since=new Date(job.waitingSince||Date.now()), elapsed=Math.max(0,Date.now()-since.getTime()), overdue=elapsed>=WAITING_MS; const days=Math.floor(elapsed/86400000), hours=Math.floor((elapsed%86400000)/3600000); return {progress:Math.min(1,elapsed/WAITING_MS),overdue,label:days?`seit ${days} Tag${days===1?"":"en"}`:`seit ${hours} Std.`,since}; }
function addWaitingActions(card,job){ const existing=card.querySelector(".waiting-actions"); if(existing){existing.remove();return;} const info=waitInfo(job), actions=document.createElement("div"); actions.className="waiting-actions"; actions.innerHTML=`<span>${info.overdue?"7 Tage ohne Antwort":"Wartet "+info.label}</span><button data-wait="archive">Archiv</button><button data-wait="resend">Erneut senden</button>`; actions.onclick=e=>{e.stopPropagation();const action=e.target.dataset.wait;if(action==="archive")setStatus(job,"archive");if(action==="resend")job.waitingSince=new Date().toISOString();if(action){save();render();}};card.querySelector(".card-footer").before(actions); }
function render(){
  const visible = jobs.filter(j => (filter === "archive" ? j.status === "archive" : j.status !== "archive") && (filter === "all" || filter === "archive" || (filter === "new" ? j.isNew : filter === "remote" ? /remote/i.test(j.location || "") : j.status === "waiting")) && `${j.company} ${j.role}`.toLowerCase().includes(query));
  document.querySelector("#totalCount").textContent = jobs.length;
  document.querySelector("#activeSearchCount").textContent = savedSearches.filter(search => search.active).length;
  board.innerHTML = "";
  columns.forEach(id => {
    const name = columnName(id); const col = document.createElement("section"); col.className="column"; col.innerHTML=`<div class="column-head"><h2>${name}</h2><span>${visible.filter(j=>j.status===id).length}</span>${id === "inbox" ? '<button class="tinder-button" title="Inbox Review">⇄</button>' : ""}<button class="column-menu" data-column="${id}" title="Archive all">•••</button></div><div class="drop-zone" data-status="${id}"></div>`;
    const zone=col.querySelector(".drop-zone"); const items=visible.filter(j=>j.status===id);
    col.querySelector(".column-menu").onclick=()=>{if(confirm(`Alle Karten aus ${name} archivieren?`)){jobs.forEach(job=>{if(job.status===id)job.status="archive"});save();render();}};
    if(id==="inbox") col.querySelector(".tinder-button").onclick=openTinder;
    if(!items.length) zone.innerHTML=`<div class="empty">${t("empty")}</div>`;
    items.forEach(job=>{
      const card=template.content.firstElementChild.cloneNode(true); card.dataset.id=job.id;
      card.querySelector(".priority").classList.add(job.priority); card.querySelector("h3").textContent=job.role; card.querySelector(".role").textContent=job.company; card.querySelector(".note").textContent=job.note; card.querySelector(".card-icons").textContent=`${job.source ? "🔎" : "✍️"} ${job.isNew ? "🆕" : ""} ${/remote/i.test(job.location || "") ? "🏠" : ""} ${job.industry === "games" ? "🎮" : ""}`;
      const contact=job.selectedContact || job.contacts?.[0]?.name; card.querySelector(".avatar").textContent=initials(contact); const arrow=card.querySelector(".arrow"); if(job.status==="waiting"){const info=waitInfo(job);card.querySelector(".next-step").textContent=info.overdue?"Antwort offen":"Wartet "+info.label;arrow.className=`wait-pie${info.overdue?" overdue":""}`;arrow.style.setProperty("--progress",info.progress);arrow.innerHTML=`<span>${info.overdue?"?":"⌛"}</span>`;arrow.title=info.overdue?"Antwort prüfen":"Wartezeit";arrow.onclick=e=>{e.stopPropagation();addWaitingActions(card,job)}}else{card.querySelector(".next-step").textContent=nextLabel(job.status);arrow.onclick=e=>{e.stopPropagation();move(job.id)}}
      card.onclick=()=>{job.isNew=false;save();openDetail(job.id)}; card.querySelector(".dots").onclick=e=>{e.stopPropagation();document.querySelectorAll(".card-popover").forEach(menu=>menu.remove());const menu=document.createElement("div");menu.className="card-popover";menu.innerHTML='<button data-action="open">Öffnen</button><button data-action="edit">Bearbeiten</button><button data-action="archive">Archivieren</button>';menu.style.left=e.clientX+"px";menu.style.top=e.clientY+"px";menu.querySelector('[data-action="open"]').onclick=()=>{menu.remove();openDetail(job.id)};menu.querySelector('[data-action="edit"]').onclick=()=>{menu.remove();openJobEditor(job.id)};menu.querySelector('[data-action="archive"]').onclick=()=>{menu.remove();setStatus(job,"archive");save();render()};document.body.append(menu);}; const grab=card.querySelector(".card-grab"); grab.addEventListener("dragstart",()=>draggingId=job.id); grab.addEventListener("dragend",()=>draggingId=null); zone.append(card);
    });
    zone.addEventListener("dragover",e=>{e.preventDefault();zone.classList.add("drag-over")}); zone.addEventListener("dragleave",()=>zone.classList.remove("drag-over")); zone.addEventListener("drop",e=>{e.preventDefault();zone.classList.remove("drag-over"); const job=jobs.find(j=>j.id===draggingId);if(job){setStatus(job,id);save();render()}}); board.append(col);
  });
}
function stageTab(status){return ({inbox:"job",contacts:"contacts",ready:"outreach",waiting:"status",archive:"status"})[status]||"job";}
function move(id){ const job=jobs.find(j=>j.id===id), at=columns.indexOf(job.status); if(at<columns.length-1){setStatus(job,columns[at+1]);save();render();openDetail(id,stageTab(job.status));} }
function openTinder(onlyNew=false){const cards=jobs.filter(job=>job.status==="inbox"&&(!onlyNew||job.isNew));let index=0;const dialog=document.querySelector("#tinderDialog"),content=document.querySelector("#tinderContent");const draw=()=>{const job=cards[index];if(!job){content.innerHTML='<h2>Keine Leads zu prüfen.</h2><p class="detail-role">Starte eine Suche und fülle deine Inbox mit neuen Treffern.</p><button class="primary" id="tinderSearch">Jetzt suchen</button>';document.querySelector("#tinderSearch").onclick=()=>{dialog.close();document.querySelector("#searchNow").click()};return;}content.innerHTML=`<p class="eyebrow">INBOX REVIEW · ${index+1}/${cards.length}</p><h2>${job.company}</h2><p class="detail-role">${job.role} · ${job.location||"Standort offen"}</p><section><p>${job.note}</p></section><div class="modal-actions"><button class="secondary" id="tinderNo">← Archiv</button><button class="primary" id="tinderYes">Kontakte →</button></div>`;document.querySelector("#tinderNo").onclick=()=>{setStatus(job,"archive");save();render();index++;draw()};document.querySelector("#tinderYes").onclick=()=>{setStatus(job,"contacts");job.isNew=false;save();render();index++;draw()}};draw();if(!dialog.open)dialog.showModal();}
function linkedInSearch(contact, company){ return `https://www.google.com/search?q=${encodeURIComponent(`site:linkedin.com/in \"${contact.name}\" \"${company}\"`)}`; }
const researchPathDefinitions=[
  {id:"executive",label:"Geschäftsführung",focus:"executive"},
  {id:"role",label:"Fachlicher Entscheider",focus:"role"},
  {id:"known-current",label:"Someone I know that works there",requiresConnections:true},
  {id:"known-past",label:"Someone I know who worked there in the past",requiresConnections:true}
];
function functionalContactTerms(role=""){const value=role.toLowerCase();if(/operations|live ops|producer|project/.test(value))return `\"Head of Operations\" OR \"Operations Director\" OR COO`;if(/product|monetization/.test(value))return `\"Head of Product\" OR \"Product Director\" OR CPO`;if(/publishing/.test(value))return `\"Head of Publishing\" OR \"Publishing Director\"`;if(/community|support/.test(value))return `\"Head of Community\" OR \"Player Support Director\"`;if(/localization/.test(value))return `\"Head of Localization\" OR \"Localization Director\"`;return `\"Head of\" OR Director OR VP`;}
function researchQuery(job,path){const base=`site:linkedin.com/in \"${job.company}\"`;if(path.focus==="executive")return `${base} (CEO OR Founder OR COO OR \"Managing Director\")`;if(path.focus==="role")return `${base} (${functionalContactTerms(job.role)})`;return `${base} \"${job.company}\"`;}
function ensureResearchPaths(job){if(!job.researchPaths){job.researchPaths=researchPathDefinitions.map(path=>({...path}));(job.contacts||[]).slice(0,2).forEach((contact,index)=>job.researchPaths[index].contact=contact);}return job.researchPaths;}
function syncContactsFromPaths(job){job.contacts=ensureResearchPaths(job).map(path=>path.contact).filter(Boolean);}
function degreeBadge(contact){const degree=String(contact?.connectionDegree||"").toLowerCase();return degree.includes("1")?"1️⃣":degree.includes("2")?"2️⃣":degree.includes("3")?"3️⃣":"◌";}
function contactMarkup(job,path,index){const contact=path.contact;if(!contact)return "";const checked=job.selectedContact===contact.name;return `<div class="path-contact"><label class="contact-check"><input type="checkbox" data-path-choice="${index}" ${checked?"checked":""}><span><strong>${contact.name}</strong><small>${degreeBadge(contact)} ${contact.title||"Entscheider"}${contact.connectionDegree?` · <em>${contact.connectionDegree}</em>`:" · <em>Verbindung nicht synchronisiert</em>"}</small></span></label><div class="contact-actions"><a class="linkedin-link" href="${contact.profileUrl||linkedInSearch(contact,job.company)}" target="_blank" rel="noreferrer" title="LinkedIn-Profil öffnen"><img src="assets/linkedin.png" alt="LinkedIn"></a><button class="delete-contact" data-delete-path="${index}" title="Kontakt entfernen">🗑️</button></div></div>`;}
async function researchPath(job,path){if(path.requiresConnections)return;const result=await getApiJson(`/api/contact-research?company=${encodeURIComponent(job.company)}&role=${encodeURIComponent(job.role)}&focus=${encodeURIComponent(path.focus||"role")}`);const contact=result.contacts?.[0];if(contact)path.contact={name:contact.name,title:contact.title,profileUrl:contact.url};job.contactsResearched=true;syncContactsFromPaths(job);}
function renderResearchPaths(job,content,id){const panel=content.querySelector('[data-tab-panel="contacts"]');if(!panel)return;const paths=ensureResearchPaths(job);panel.innerHTML=`<div class="research-toolbar"><button class="secondary" id="researchAll"><img class="brave-icon" src="assets/brave.png" alt="">Kontakte recherchieren</button></div><p id="researchStatus" class="research-status"></p><div class="research-paths">${paths.map((path,index)=>`<article class="research-path"><header><div><strong>${path.label}</strong><small>${path.requiresConnections?"Abgleich mit deinen LinkedIn-Verbindungen":"Öffentliche LinkedIn-Profile über Brave"}</small></div><button class="path-menu" data-path-menu="${index}" title="Optionen">•••</button></header>${path.contact?contactMarkup(job,path,index):path.requiresConnections?`<p class="research-note">Noch keine Verbindungsdaten importiert. Du kannst einen passenden Kontakt trotzdem manuell ergänzen.</p>`:`<p class="research-note">Noch kein Treffer für diesen Pfad.</p>`}</article>`).join("")}</div>${job.status==="contacts"?`<button id="advanceReady" class="primary advance-ready" ${job.selectedContact?"":"disabled"}>Bereit zum Anschreiben →</button>`:""}`;
  const status=panel.querySelector("#researchStatus"), run=async index=>{const path=paths[index];status.textContent="Recherche läuft …";try{await researchPath(job,path);save();render();openDetail(id,"contacts");}catch(error){status.textContent=error.message||"Recherche konnte nicht abgeschlossen werden.";}};
  panel.querySelector("#researchAll").onclick=async event=>{const open=paths.filter(path=>!path.contact&&!path.requiresConnections);if(!open.length){status.textContent="Alle automatischen Recherchepfade sind bereits gefüllt.";return;}event.currentTarget.disabled=true;status.textContent="Recherche läuft …";try{for(const path of open)await researchPath(job,path);save();render();openDetail(id,"contacts");}catch(error){status.textContent=error.message||"Recherche konnte nicht abgeschlossen werden.";}finally{event.currentTarget.disabled=false;}};
  panel.querySelectorAll("[data-path-choice]").forEach(choice=>choice.onchange=()=>{const path=paths[Number(choice.dataset.pathChoice)];job.selectedContact=choice.checked?path.contact.name:"";save();panel.querySelector("#advanceReady")?.toggleAttribute("disabled",!job.selectedContact);});
  panel.querySelectorAll("[data-delete-path]").forEach(button=>button.onclick=()=>{const path=paths[Number(button.dataset.deletePath)];if(job.selectedContact===path.contact?.name)job.selectedContact="";path.contact=null;syncContactsFromPaths(job);save();render();openDetail(id,"contacts");});
  panel.querySelectorAll("[data-path-menu]").forEach(button=>button.onclick=event=>{document.querySelectorAll(".card-popover").forEach(menu=>menu.remove());const index=Number(button.dataset.pathMenu),path=paths[index],menu=document.createElement("div");menu.className="card-popover path-popover";menu.style.left=event.clientX+"px";menu.style.top=event.clientY+"px";menu.innerHTML=`${path.requiresConnections?"":`<button data-research-one><img class="menu-brave" src="assets/brave.png" alt="">Diesen Pfad recherchieren</button>`}<button data-manual>Manuell einfügen</button>${path.requiresConnections?"":`<button data-show-query>？ Suchanfrage ansehen</button>`}`;menu.querySelector("[data-research-one]")?.addEventListener("click",()=>{menu.remove();run(index);});menu.querySelector("[data-manual]").onclick=()=>{menu.remove();manualContactTarget={jobId:id,pathId:path.id};document.querySelector("#manualContactTitle").textContent=path.label;document.querySelector("#manualContactDialog").showModal();document.querySelector("#manualContactName").focus();};menu.querySelector("[data-show-query]")?.addEventListener("click",()=>{menu.remove();document.querySelector("#researchQuery").textContent=researchQuery(job,path);document.querySelector("#queryDialog").showModal();});detailDialog.append(menu);});
  panel.querySelector("#advanceReady")?.addEventListener("click",()=>{if(!job.selectedContact)return;setStatus(job,"ready");save();render();openDetail(id,"outreach");});
}
function openDetail(id,initialTab=stageTab(jobs.find(j=>j.id===id)?.status)){ const job=jobs.find(j=>j.id===id); const role=job.role.toLowerCase(), functional=role.includes("marketing")||role.includes("growth") ? "CMO OR \"Head of Marketing\"" : role.includes("operations") ? "COO OR \"Head of Operations\"" : "Hiring Manager"; const research=[["Geschäftsführung", `site:linkedin.com/in "${job.company}" (CEO OR Founder OR Geschäftsführer)`],["Fachlicher Entscheider", `site:linkedin.com/in "${job.company}" (${functional})`]]; const candidateList=(job.contacts||[]).map((c,index)=>`<div class="contact"><div><strong>${c.name}</strong><span>${c.title}</span></div><div class="contact-actions"><a class="link-btn" target="_blank" rel="noreferrer" href="${c.profileUrl || linkedInSearch(c,job.company)}">Profil ↗</a><button class="choose-contact" data-index="${index}">Auswählen</button></div></div>`).join(""); const researchList=job.status !== "inbox" && job.contacts.length<2 ? `<p class="research-note">Zwei passende Recherchepfade – Google öffnet die Profile. Name und Titel dann hier übernehmen.</p>${research.map(item=>`<div class="contact"><div><strong>${item[0]}</strong><span>${job.company}</span></div><a class="link-btn" target="_blank" rel="noreferrer" href="${googleSearch(item[1])}">Google-Suche ↗</a></div>`).join("")}<form id="contactForm" class="form-grid"><label>Name<input id="contactName" placeholder="Name aus dem Profil"></label><label>Rolle<input id="contactTitle" placeholder="z. B. CEO"></label><button class="secondary">Kontakt hinzufügen</button></form>` : ""; const target=job.selectedContact || job.contacts?.[0]?.name || "[Name]"; const sourceInfo=`<section><h4>JOB & QUELLE</h4><p>${job.location || "Standort offen"} · ${job.source || "Manuell hinzugefügt"}</p>${job.jobLink ? `<a class="link-btn" target="_blank" rel="noreferrer" href="${job.jobLink}">Stellenanzeige öffnen ↗</a><iframe class="source-preview" title="Vorschau der Stellenanzeige" src="${job.jobLink}" loading="lazy" referrerpolicy="no-referrer"></iframe><p class="preview-hint">Falls die Quelle das Einbetten sperrt, öffne sie über den Link oben.</p>` : ""}${job.publishedAt ? `<p class="research-note">Veröffentlicht: ${new Date(job.publishedAt).toLocaleDateString("de-DE")}</p>` : ""}</section>`;
  document.querySelector("#detailContent").innerHTML=`<p class="eyebrow">${job.status.toUpperCase()} · ${job.priority === "high" ? "HOHE PRIORITÄT" : "PRIORITÄT MITTEL"}</p><h2>${job.company}</h2><p class="detail-role">${job.role}${job.location ? " · " + job.location : ""}</p><section><h4>WARUM DIESER LEAD</h4><p>${job.note}</p></section>${sourceInfo}${job.status === "inbox" ? '<section class="detail-actions"><button class="secondary archive-detail" id="archiveDetail">Archivieren</button><button class="primary next-detail" id="detailNext">Zu Kontakten →</button></section>' : `<section><h4>KONTAKTE & RECHERCHE</h4><button class="secondary" id="researchContacts">✨ Kontakte recherchieren</button><div id="researchStatus"></div>${candidateList}${researchList}</section>`}${["ready","waiting"].includes(job.status) ? `<section><h4>KONTAKTANFRAGE · ENTWURF</h4><div class="message">Hallo ${target},\n\nich habe gesehen, dass ${job.company} gerade eine:n ${job.role} sucht. Während ihr die Position besetzt, könnte ich euch bei den wichtigsten Themen kurzfristig unterstützen und schnell Struktur in die Umsetzung bringen.\n\nWäre ein kurzer Austausch sinnvoll?</div><button class="copy" id="copyMessage">Text kopieren</button></section>` : ""}`;
  const content=document.querySelector("#detailContent"), sections=[...content.querySelectorAll("section")], why=sections[0]; sections.slice(1).forEach(section=>{const title=section.querySelector("h4")?.textContent||"";section.dataset.tabPanel=title.includes("ENTWURF")?"outreach":title.includes("KONTAKT")?"contacts":"job";}); if(!content.querySelector('[data-tab-panel="contacts"]')){const panel=document.createElement("section");panel.dataset.tabPanel="contacts";panel.innerHTML="<p class=\"research-note\">Sobald du den Lead zu Kontakten schiebst, kannst du passende Personen recherchieren und auswählen.</p>";content.append(panel)} if(!content.querySelector('[data-tab-panel="outreach"]')){const panel=document.createElement("section");panel.dataset.tabPanel="outreach";panel.innerHTML="<p class=\"research-note\">Der Entwurf wird nach der Kontakt-Auswahl vorbereitet.</p>";content.append(panel)} const info=job.status==="waiting"?waitInfo(job):null,statusPanel=document.createElement("section");statusPanel.dataset.tabPanel="status";statusPanel.className="detail-status";statusPanel.innerHTML=info?`<h4>WAITING</h4><strong>${info.overdue?"Antwort prüfen":"Wartet "+info.label}</strong><p>${info.overdue?"Seit sieben Tagen ist keine Antwort eingegangen.":"Die 7-Tage-Frist läuft ab dem Zeitpunkt, an dem die Karte in Waiting verschoben wurde."}</p><div class="detail-wait-actions"><button class="warn" id="waitArchive">Archivieren</button><button id="waitResend">Erneut senden</button></div>`:`<h4>STATUS</h4><strong>${columnName(job.status)}</strong><p>Der aktuelle Schritt dieser Outreach-Pipeline.</p>`;content.append(statusPanel);content.querySelectorAll('[data-tab-panel] > h4').forEach(header=>header.remove()); why.insertAdjacentHTML("afterend",'<nav class="detail-tabs" aria-label="Lead-Details"><button class="detail-tab active" data-tab="job">💼 Job & Quelle</button><button class="detail-tab" data-tab="contacts">♧ Kontakte & Recherche</button><button class="detail-tab" data-tab="outreach">✈ Outreach</button><button class="detail-tab" data-tab="status">◷ Status</button></nav>'); const switchTab=tab=>{content.querySelectorAll(".detail-tab").forEach(button=>button.classList.toggle("active",button.dataset.tab===tab));content.querySelectorAll("[data-tab-panel]").forEach(panel=>panel.hidden=panel.dataset.tabPanel!==tab)};content.querySelectorAll(".detail-tab").forEach(button=>button.onclick=()=>switchTab(button.dataset.tab));switchTab(initialTab);
  if(job.status!=="inbox"){const panel=content.querySelector('[data-tab-panel="contacts"]'),rows=[...panel.querySelectorAll(".contact")].slice(0,job.contacts.length);rows.forEach((row,index)=>{const contact=job.contacts[index],checked=job.selectedContact===contact.name;row.classList.add("contact-candidate");row.innerHTML=`<label class="contact-check"><input type="checkbox" data-contact-choice="${index}" ${checked?"checked":""}><span><strong>${contact.name}</strong><small>${contact.title||"Entscheider"} · <em>${contact.connectionDegree||"Verbindung nicht synchronisiert"}</em></small></span></label><div class="contact-actions"><a class="linkedin-link" href="${contact.profileUrl||linkedInSearch(contact,job.company)}" target="_blank" rel="noreferrer" title="LinkedIn-Profil öffnen"><img src="assets/linkedin.png" alt="LinkedIn"></a><button class="delete-contact" data-delete-contact="${index}" title="Kontakt entfernen">⌫</button></div>`});if(job.status==="contacts"){const advance=document.createElement("button");advance.id="advanceReady";advance.className="primary advance-ready";advance.disabled=!job.selectedContact;advance.textContent="Bereit zum Anschreiben →";panel.append(advance);advance.onclick=()=>{if(!job.selectedContact)return;setStatus(job,"ready");save();render();openDetail(id,"outreach")}};panel.querySelectorAll("[data-contact-choice]").forEach(choice=>choice.onchange=()=>{job.selectedContact=choice.checked?job.contacts[Number(choice.dataset.contactChoice)].name:null;save();panel.querySelector("#advanceReady")?.toggleAttribute("disabled",!job.selectedContact)});panel.querySelectorAll("[data-delete-contact]").forEach(button=>button.onclick=()=>{const index=Number(button.dataset.deleteContact),removed=job.contacts[index];job.contacts.splice(index,1);if(job.selectedContact===removed.name)job.selectedContact="";save();render();openDetail(id,"contacts")})}
  if(job.contactsResearched){const tune=document.createElement("button");tune.className="secondary tune-job";tune.textContent="Not fitting? Adjust job and try again";tune.onclick=()=>{detailDialog.close();openJobEditor(id,true)};content.querySelector('[data-tab-panel="contacts"]')?.append(tune)}
  document.querySelectorAll(".choose-contact").forEach(button=>button.onclick=()=>{job.selectedContact=job.contacts[Number(button.dataset.index)].name;save();render();openDetail(id)}); const contactForm=document.querySelector("#contactForm"); if(contactForm) contactForm.onsubmit=event=>{event.preventDefault();const name=document.querySelector("#contactName").value.trim(),title=document.querySelector("#contactTitle").value.trim();if(name){job.contacts.push({name,title:title||"Entscheider"});save();render();openDetail(id);}};
  const detailNext=document.querySelector("#detailNext"); if(detailNext) detailNext.onclick=()=>{setStatus(job,"contacts");job.isNew=false;save();render();openDetail(id,"contacts");}; const archiveDetail=document.querySelector("#archiveDetail");if(archiveDetail)archiveDetail.onclick=()=>{setStatus(job,"archive");save();render();detailDialog.close();};
  const researchButton=document.querySelector("#researchContacts"); if(researchButton){researchButton.innerHTML='<img class="brave-icon" src="assets/brave.png" alt="">Kontakte recherchieren';const queryButton=document.createElement("button");queryButton.className="query-button";queryButton.title="Aktuelle Brave-Suche anzeigen";queryButton.textContent="?";researchButton.after(queryButton);queryButton.onclick=()=>{document.querySelector("#researchQuery").textContent=`site:linkedin.com/in "${job.company}" (CEO OR Founder OR "${job.role}" OR "Head of" OR Director)`;document.querySelector("#queryDialog").showModal()};researchButton.onclick=async()=>{const status=document.querySelector("#researchStatus");researchButton.disabled=true;status.textContent="Recherche läuft …";try{const result=await getApiJson(`/api/contact-research?company=${encodeURIComponent(job.company)}&role=${encodeURIComponent(job.role)}`);job.contacts=result.contacts.map(contact=>({name:contact.name,title:contact.title,profileUrl:contact.url}));job.contactsResearched=true;save();render();openDetail(id,"contacts")}catch(error){status.textContent=error.message}finally{researchButton.disabled=false}}};
  const flowTabs=["job","contacts","outreach","status"],flowIndex=flowTabs.indexOf(stageTab(job.status)),tabNodes=[...content.querySelectorAll(".detail-tab")];tabNodes.forEach((tab,index)=>{if(index<flowIndex){tab.classList.add("past-tab");tab.insertAdjacentHTML("afterbegin",'<span class="tab-state done">✓</span>')}if(index>flowIndex){tab.classList.add("future-tab");tab.disabled=true;if(index>flowIndex+1)tab.insertAdjacentHTML("afterbegin",'<span class="tab-state waiting">⌛</span>')}});if(flowIndex>=0&&flowIndex<flowTabs.length-1){const nextDisabled=job.status==="contacts"&&!job.selectedContact,arrow=document.createElement("button");arrow.className="tab-transition";arrow.disabled=nextDisabled;arrow.title=nextDisabled?"Bitte zuerst einen Kontakt auswählen.":"Zum nächsten Schritt";arrow.textContent="→";arrow.onclick=event=>{event.stopPropagation();move(id)};tabNodes[flowIndex].after(arrow);}
  if(job.status!=="inbox")renderResearchPaths(job,content,id);
  const copyMessage=document.querySelector("#copyMessage"); if(copyMessage) copyMessage.onclick=e=>{navigator.clipboard.writeText(document.querySelector(".message").innerText);e.target.textContent="Kopiert ✓";}; const waitArchive=document.querySelector("#waitArchive"),waitResend=document.querySelector("#waitResend"); if(waitArchive) waitArchive.onclick=()=>{setStatus(job,"archive");save();render();detailDialog.close()};if(waitResend) waitResend.onclick=()=>{job.waitingSince=new Date().toISOString();save();render();openDetail(id,"status")}; if(!detailDialog.open)detailDialog.showModal();
}
function openJobEditor(id=null,fromContacts=false){editingJobId=id;returnToContacts=fromContacts;const dialog=document.querySelector("#jobDialog"),job=id&&jobs.find(item=>item.id===id),form=dialog.querySelector("form");form.reset();document.querySelector("#jobDialog .eyebrow").textContent=job?"LEAD BEARBEITEN":"NEUER LEAD";document.querySelector("#jobDialog h2").textContent=job?"Job-Details bearbeiten":"Job zur Pipeline hinzufügen";document.querySelector("#saveJob").textContent=job?"Änderungen speichern":"Zur Inbox";if(job){document.querySelector("#companyInput").value=job.company||"";document.querySelector("#roleInput").value=job.role||"";document.querySelector("#locationInput").value=job.location||"";document.querySelector("#linkInput").value=job.jobLink||"";document.querySelector("#noteInput").value=job.note||"";}if(!dialog.open)dialog.showModal();}
document.querySelector("#addJob").onclick=()=>openJobEditor();
document.querySelector("#saveJob").onclick=e=>{const company=document.querySelector("#companyInput").value.trim(),role=document.querySelector("#roleInput").value.trim(),rawLink=document.querySelector("#linkInput").value.trim(),jobLink=rawLink&&!/^https?:\/\//i.test(rawLink)?`https://${rawLink}`:rawLink;if(!company||!role){e.preventDefault();return;}e.preventDefault();const existing=editingJobId&&jobs.find(job=>job.id===editingJobId);if(existing){Object.assign(existing,{company,role,location:document.querySelector("#locationInput").value.trim(),jobLink,note:document.querySelector("#noteInput").value.trim()||existing.note});}else jobs.unshift({id:Date.now(),company,role,location:document.querySelector("#locationInput").value.trim(),jobLink,status:"inbox",priority:"medium",note:document.querySelector("#noteInput").value.trim()||"Neu hinzugefügt – Kontakt recherchieren.",contacts:[]});const targetId=existing?.id;save();render();document.querySelector("#jobDialog").close();document.querySelector("#jobDialog form").reset();if(targetId&&returnToContacts){returnToContacts=false;openDetail(targetId,"contacts")}editingJobId=null;};
document.querySelector(".detail-close").onclick=()=>detailDialog.close(); document.querySelector("#search").oninput=e=>{query=e.target.value.toLowerCase();render()}; document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()}); document.querySelector("#focusButton").onclick=()=>document.body.classList.toggle("focus");
async function hydrateCloudWorkspace(){
  await window.signalboardAuth?.ready;
  try {
    const cloud = await window.signalboardAuth?.loadState();
    if (cloud?.jobs?.length || cloud?.searches?.length || cloud?.ignored_jobs?.length) {
      jobs = cloud.jobs || [];
      savedSearches = cloud.searches || [];
      ignoredJobs = cloud.ignored_jobs || [];
    } else if (window.signalboardAuth?.configured && window.signalboardAuth.user) {
      save();
    }
  } catch (error) { console.warn("Cloud-Workspace konnte nicht geladen werden:", error.message); }
  render();
}
hydrateCloudWorkspace();
setInterval(render,60000);
window.addEventListener("signalboard-auth-change", () => hydrateCloudWorkspace());
window.addEventListener("signalboard-language-changed", render);

function googleSearch(query) {
  return `https://www.google.com/search?q=${encodeURIComponent(query)}`;
}

async function getApiJson(url) {
  const response = await fetch(url, { headers: { Accept: "application/json" } });
  const contentType = response.headers.get("content-type") || "";
  const body = await response.text();
  if (!contentType.includes("application/json")) throw new Error("Die lokale Such-API hat keine gültige Antwort geliefert. Bitte Signalboard einmal neu laden.");
  const payload = JSON.parse(body);
  if (!response.ok || payload.error) throw new Error(payload.error || "Die Suche konnte gerade nicht gestartet werden.");
  return payload;
}

function showDiscoveredJobs(items, label, tabSearchIds = null) {
  const area = document.querySelector("#discoveryResults");
  items=items.filter(job=>!isKnownJob(job));
  const dialog=document.querySelector("#resultsDialog"); if(!dialog.open)dialog.showModal();
  if (!items.length) { pendingDiscoveryCount=0;updateSearchButton();area.innerHTML = '<div class="discovery-empty">Keine Treffer in den angebundenen Quellen. Suchparameter anpassen oder Google Jobs ergänzend nutzen.</div>'; return; }
  pendingDiscoveryCount=items.length;updateSearchButton();
  const groupOf=job=>String(job.searchId||"other"),groups=(tabSearchIds?.length?tabSearchIds.map(String):[...new Set(items.map(groupOf))]),showTabs=groups.length>1,tabTitle=id=>id==="other"?"Other":savedSearches.find(search=>String(search.id)===id)?.title||"Suchauftrag",activeGroup=groups.find(id=>items.some(job=>groupOf(job)===id))||groups[0];
  area.innerHTML = `<div class="discovery-head"><div><h3>${items.length} neue Job-Leads</h3></div><button class="reset-results" id="searchAgain">↻ Nochmal suchen</button></div>${showTabs?`<div class="result-tabs">${groups.map((id,index)=>`<button class="result-tab ${id===activeGroup?"active":""}" data-result-tab="${id}">${tabTitle(id)} <b>${items.filter(job=>groupOf(job)===id).length}</b></button>`).join("")}</div>`:""}<div class="discovery-list">${items.map((job, index) => `<article class="result-row" data-search-group="${groupOf(job)}" ${showTabs&&groupOf(job)!==activeGroup?"hidden":""}><div class="result-copy"><strong>${job.company} · ${job.title}</strong><span>${job.location || "Standort offen"} · ${job.source}</span><p class="result-desc">${job.description || ""}</p></div><div class="result-actions"><a target="_blank" rel="noreferrer" href="${job.url}">Job ↗</a><button data-result="${index}">Zur Inbox</button><button class="dismiss-result" data-dismiss="${index}" title="Treffer ausblenden">×</button></div></article>`).join("")}<div class="result-tab-empty" hidden>Keine neuen Treffer für diesen Suchauftrag.</div></div>`;
  const updateResultCount=()=>{const remaining=[...area.querySelectorAll(".result-row")];pendingDiscoveryCount=remaining.length;updateSearchButton();if(!remaining.length){area.innerHTML='<div class="discovery-complete"><strong>All done!</strong><span>Check again later.</span></div>';return;}area.querySelector(".discovery-head h3").textContent=`${remaining.length} neue Job-Leads`;area.querySelectorAll("[data-result-tab]").forEach(tab=>{tab.querySelector("b").textContent=remaining.filter(row=>row.dataset.searchGroup===tab.dataset.resultTab).length;});};
  area.querySelector("#searchAgain").onclick=()=>{pendingDiscoveryCount=0;updateSearchButton();dialog.close();document.querySelector("#searchNow").click();};
  area.querySelectorAll("[data-result-tab]").forEach(tab=>tab.onclick=()=>{const id=tab.dataset.resultTab;area.querySelectorAll("[data-result-tab]").forEach(item=>item.classList.toggle("active",item===tab));const rows=[...area.querySelectorAll(".result-row")];rows.forEach(row=>row.hidden=row.dataset.searchGroup!==id);area.querySelector(".result-tab-empty").hidden=rows.some(row=>row.dataset.searchGroup===id);});
  area.querySelectorAll("[data-dismiss]").forEach(button=>button.onclick=()=>{const job=items[Number(button.dataset.dismiss)];ignoreJob(job);button.closest(".result-row").classList.add("result-leaving");setTimeout(()=>{button.closest(".result-row")?.remove();updateResultCount()},220)});
  area.querySelectorAll("[data-result]").forEach(button => button.onclick = () => {
    const job = items[Number(button.dataset.result)];
    if (isKnownJob(job)) { button.textContent = "Schon da"; button.disabled = true; return; }
    jobs.unshift({ id: Date.now() + Number(button.dataset.result), company: job.company, role: job.title, location: job.location, jobLink: job.url, source:job.source,searchId:job.searchId,publishedAt:job.publishedAt,status: "inbox", priority: "medium", isNew:true, note: job.description || `Neu über ${job.source} gefunden.`, contacts: [] });
    save(); render(); button.textContent = "✓ In Inbox"; button.classList.add("added"); button.disabled = true; button.closest(".result-row").querySelector(".result-desc")?.remove();button.closest(".result-row").classList.add("result-leaving");setTimeout(()=>{button.closest(".result-row")?.remove();updateResultCount()},420);
  });
}

async function runDiscovery(id) {
  const search = savedSearches.find(item => item.id === id), area = document.querySelector("#discoveryResults");
  area.innerHTML = `<div class="discovery-empty">Durchsuche Jobquellen für <strong>${search.title}</strong> …</div>`;
  try {
    const params = new URLSearchParams({ title: search.title, location: search.location, keywords: search.keywords, arbeitnow:search.sources?.arbeitnow!==false,remotive:search.sources?.remotive!==false,braveGames:search.sources?.braveGames!==false,braveTech:search.sources?.braveTech!==false });
    const response = await getApiJson(`/api/discover-jobs?${params}`);
    showDiscoveredJobs(response.jobs.map(job=>({...job,searchId:search.id})), `${search.title} · ${search.location || "alle Standorte"}`, [search.id]);
  } catch (error) { area.innerHTML = `<div class="discovery-empty">${error.message || "Jobquellen sind gerade nicht erreichbar."}</div>`; }
}

function renderSavedSearches() {
  const list = document.querySelector("#savedSearchList");
  list.innerHTML = savedSearches.map(search => `<div class="search-row"><input type="checkbox" data-toggle="${search.id}" ${search.active ? "checked" : ""}><div class="search-copy"><strong>${search.title}</strong><span>${[search.location, search.keywords].filter(Boolean).join(" · ")}</span></div><button class="edit-search" data-edit="${search.id}" title="Bearbeiten">✎</button><button data-run="${search.id}">Suchen ↗</button><button class="delete-search" data-delete="${search.id}">×</button></div>`).join("");
  list.querySelectorAll("[data-toggle]").forEach(input => input.onchange = () => { savedSearches.find(search => search.id === Number(input.dataset.toggle)).active = input.checked; save(); render(); });
  list.querySelectorAll("[data-run]").forEach(button => button.onclick = () => runDiscovery(Number(button.dataset.run)));
  list.querySelectorAll("[data-edit]").forEach(button => button.onclick = () => {
    const search = savedSearches.find(item => item.id === Number(button.dataset.edit));
    editingSearchId = search.id;
    document.querySelector("#searchTitle").value = search.title;
    document.querySelector("#searchLocation").value = search.location || "";
    document.querySelector("#searchKeywords").value = search.keywords || "";
    document.querySelector("#sourceArbeitnow").checked = search.sources?.arbeitnow !== false;
    document.querySelector("#sourceRemotive").checked = search.sources?.remotive !== false;
    document.querySelector("#sourceBraveGames").checked = search.sources?.braveGames !== false;
    document.querySelector("#sourceBraveTech").checked = search.sources?.braveTech !== false;
    document.querySelector("#searchForm button").textContent = "Änderungen speichern";
    document.querySelector("#searchTitle").focus();
  });
  list.querySelectorAll("[data-delete]").forEach(button => button.onclick = () => { savedSearches = savedSearches.filter(search => search.id !== Number(button.dataset.delete)); save(); renderSavedSearches(); render(); });
}

document.querySelector("#openSearches").onclick = () => { renderSavedSearches(); document.querySelector("#searchDialog").showModal(); };
document.querySelector(".search-close").onclick = () => { editingSearchId = null; document.querySelector("#searchForm").reset(); document.querySelector("#searchForm button").textContent = "＋ Suchauftrag anlegen"; document.querySelector("#searchDialog").close(); };
document.querySelector("#searchForm").onsubmit = event => {
  event.preventDefault();
  const values = { title: document.querySelector("#searchTitle").value.trim(), location: document.querySelector("#searchLocation").value.trim(), keywords: document.querySelector("#searchKeywords").value.trim(), sources: { arbeitnow: document.querySelector("#sourceArbeitnow").checked, remotive: document.querySelector("#sourceRemotive").checked, braveGames:document.querySelector("#sourceBraveGames").checked, braveTech:document.querySelector("#sourceBraveTech").checked } };
  const existing = editingSearchId && savedSearches.find(search => search.id === editingSearchId);
  if (existing) Object.assign(existing, values);
  else savedSearches.push({ id: Date.now(), ...values, active: true });
  editingSearchId = null; save(); event.target.reset(); document.querySelector("#searchForm button").textContent = "＋ Suchauftrag anlegen"; renderSavedSearches(); render();
};

document.querySelector("#autofill").onclick = async () => {
  const link = document.querySelector("#linkInput").value.trim(), status = document.querySelector("#autofillStatus");
  if (!link) { status.textContent = "Bitte zuerst einen Job-Link einfügen."; return; }
  status.textContent = "Jobseite wird gelesen …";
  try {
    const result = await fetch(`/api/job-preview?url=${encodeURIComponent(link)}`).then(response => response.json());
    if (result.error) throw new Error(result.error);
    document.querySelector("#companyInput").value = result.company;
    document.querySelector("#roleInput").value = result.title;
    document.querySelector("#locationInput").value = result.location;
    status.textContent = `Daten von ${result.source} übernommen – bitte kurz prüfen.`;
  } catch (error) { status.textContent = error.message || "Auto-Füllung nicht möglich."; }
};
document.querySelectorAll("dialog").forEach(dialog => dialog.addEventListener("click", event => { if (event.target === dialog) dialog.close(); }));
document.addEventListener("pointerdown",event=>{if(!event.target.closest(".card-popover")&&!event.target.closest(".dots,.path-menu"))document.querySelectorAll(".card-popover").forEach(menu=>menu.remove());});
document.querySelector(".tinder-close").onclick=()=>document.querySelector("#tinderDialog").close();
document.querySelector(".results-close").onclick=()=>document.querySelector("#resultsDialog").close();
document.querySelector(".query-close").onclick=()=>document.querySelector("#queryDialog").close();
document.querySelectorAll("#closeManualContact,#cancelManualContact").forEach(button=>button.onclick=()=>{manualContactTarget=null;document.querySelector("#manualContactDialog").close();document.querySelector("#manualContactDialog form").reset();});
document.querySelector("#saveManualContact").onclick=event=>{event.preventDefault();if(!manualContactTarget)return;const job=jobs.find(item=>item.id===manualContactTarget.jobId),path=job&&ensureResearchPaths(job).find(item=>item.id===manualContactTarget.pathId),name=document.querySelector("#manualContactName").value.trim(),role=document.querySelector("#manualContactRole").value.trim(),rawLink=document.querySelector("#manualContactLink").value.trim();if(!job||!path||!name)return;path.contact={name,title:role||"Entscheider",profileUrl:rawLink&&!/^https?:\/\//i.test(rawLink)?`https://${rawLink}`:rawLink};syncContactsFromPaths(job);save();manualContactTarget=null;document.querySelector("#manualContactDialog").close();document.querySelector("#manualContactDialog form").reset();render();openDetail(job.id,"contacts");};

document.querySelector("#searchNow").onclick = async event => {
  if(pendingDiscoveryCount>0&&document.querySelector("#discoveryResults .result-row")){const dialog=document.querySelector("#resultsDialog");if(!dialog.open)dialog.showModal();return;}
  const button = event.currentTarget, active = savedSearches.filter(search => search.active);
  button.disabled = true; button.textContent = "◌ Suche läuft …";
  let found = [];
  for (const search of active) {
    try {
      const params = new URLSearchParams({ title: search.title, location: search.location, keywords: search.keywords, arbeitnow: search.sources?.arbeitnow !== false, remotive: search.sources?.remotive !== false, braveGames:search.sources?.braveGames!==false,braveTech:search.sources?.braveTech!==false });
      const response = await getApiJson(`/api/discover-jobs?${params}`);
      found.push(...(response.jobs||[]).map(job=>({...job,searchId:search.id})));
    } catch {}
  }
  const unique=[...new Map(found.map(job=>[jobKey(job),job])).values()]; button.disabled = false; if(unique.length)showDiscoveredJobs(unique,"Alle aktiven Suchaufträge",active.map(search=>search.id));else{pendingDiscoveryCount=0;button.textContent="Keine neuen Jobs";setTimeout(updateSearchButton,1800);}
};
